### ISSUE TITLE
In Bestellungsaufgabe wird die angezeigte Anzahl nicht immer aktualisiert

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#26]
Wenn eigentlich eine neue Bestellung aufgegeben werden soll, bleiben Werte von einer vorherigen Anzeige stehen

**Comment by marvinmai** [comment]
@Nunay 
Fehlermeldung, als ich eigentlich eine neue Bestellung aufgeben wollte, die alten noch angezeigt wurden, und ich ohne was neues hinzuzufügen auf Bestellen gedrückt habe:

```
03-18 16:58:28.318 29548-29575/dhbw.sa.kassensystemapplication I/art: Unable to resolve java.lang.Class<org.joda.time.base.AbstractDateTime> annotation class 3592
03-18 16:58:28.320 29548-29575/dhbw.sa.kassensystemapplication I/art: Unable to resolve java.lang.Class<org.joda.time.base.AbstractInstant> annotation class 3592
03-18 16:58:28.326 29548-29575/dhbw.sa.kassensystemapplication I/art: Unable to resolve java.lang.Class<org.joda.time.DateTime> annotation class 3591
03-18 16:58:56.032 29548-29567/dhbw.sa.kassensystemapplication D/OpenGLRenderer: endAllActiveAnimators on 0xb1c5f980 (DropDownListView) with handle 0x7902f250
03-18 16:58:56.484 29548-29548/dhbw.sa.kassensystemapplication I/System.out: Bitte wählen Sie einen Tisch aus
03-18 16:59:03.354 29548-29567/dhbw.sa.kassensystemapplication D/OpenGLRenderer: endAllActiveAnimators on 0xb1c60780 (DropDownListView) with handle 0xaef1d360
03-18 16:59:03.947 29548-29853/dhbw.sa.kassensystemapplication I/art: Unable to resolve java.lang.Class<org.joda.time.base.AbstractDateTime> annotation class 3592
03-18 16:59:03.950 29548-29853/dhbw.sa.kassensystemapplication I/art: Unable to resolve java.lang.Class<org.joda.time.base.AbstractInstant> annotation class 3592
03-18 16:59:03.957 29548-29853/dhbw.sa.kassensystemapplication I/art: Unable to resolve java.lang.Class<org.joda.time.DateTime> annotation class 3591
03-18 16:59:21.722 29548-29893/dhbw.sa.kassensystemapplication W/RestTemplate: POST request for "http://192.168.0.5:8080/api/orderedItem" resulted in 404 (); invoking error handler
03-18 16:59:21.729 29548-29893/dhbw.sa.kassensystemapplication W/System.err: org.springframework.web.client.HttpClientErrorException: 404 
03-18 16:59:21.730 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
03-18 16:59:21.730 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:585)
03-18 16:59:21.730 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:541)
03-18 16:59:21.732 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:499)
03-18 16:59:21.732 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
03-18 16:59:21.733 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at dhbw.sa.kassensystemapplication.fragment.ItemSelectFragment$UpdateOrder.doInBackground(ItemSelectFragment.java:444)
03-18 16:59:21.734 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at dhbw.sa.kassensystemapplication.fragment.ItemSelectFragment$UpdateOrder.doInBackground(ItemSelectFragment.java:428)
03-18 16:59:21.734 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-18 16:59:21.734 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-18 16:59:21.736 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-18 16:59:21.736 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-18 16:59:21.737 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-18 16:59:21.737 29548-29893/dhbw.sa.kassensystemapplication W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-18 16:59:21.931 29548-29894/dhbw.sa.kassensystemapplication I/System.out: 200
03-18 16:59:21.931 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 1 Table Name: A1 is the Table Avialable: true
03-18 16:59:21.931 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 2 Table Name: A2 is the Table Avialable: true
03-18 16:59:21.931 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 4 Table Name: B1 is the Table Avialable: true
03-18 16:59:21.931 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 5 Table Name: B2 is the Table Avialable: true
03-18 16:59:21.932 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 6 Table Name: B3 is the Table Avialable: true
03-18 16:59:21.932 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 7 Table Name: B66 is the Table Avialable: true
03-18 16:59:21.932 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 8 Table Name: B36 is the Table Avialable: true
03-18 16:59:21.932 29548-29894/dhbw.sa.kassensystemapplication I/System.out: Table ID: 9 Table Name: B33 is the Table Avialable: true
```

**Comment by Nunay** [comment]
Lag an der nicht gelöschenten Order bzw OrderedItem
