### ISSUE TITLE
Absturz beim Bezahlen

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#27]
Als sich eine Bestellung bezahlen wollte, die vorher bereits in der DB existiert hat, ist die App mit der unten stehenden Fehlermeldung abgestürzt. Der Absturz passierte als ich auf den Button "Bezahlen" in der Bestellübersicht gedrückt habe.

Allerdings bekomme ich den Fehler gerade nicht mehr reproduziert.

```
03-18 16:47:35.516 27525-27525/dhbw.sa.kassensystemapplication D/AndroidRuntime: Shutting down VM
03-18 16:47:35.517 27525-27525/dhbw.sa.kassensystemapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: dhbw.sa.kassensystemapplication, PID: 27525
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
                                                                                     at dhbw.sa.kassensystemapplication.fragment.ItemSelectFragment.showPayFragment(ItemSelectFragment.java:552)
                                                                                     at dhbw.sa.kassensystemapplication.fragment.ItemSelectFragment.access$1000(ItemSelectFragment.java:45)
                                                                                     at dhbw.sa.kassensystemapplication.fragment.ItemSelectFragment$GetOrderedItems.onPostExecute(ItemSelectFragment.java:531)
                                                                                     at dhbw.sa.kassensystemapplication.fragment.ItemSelectFragment$GetOrderedItems.onPostExecute(ItemSelectFragment.java:488)
                                                                                     at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                                     at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Nunay** [comment]
Wahrscheinlich durch mehrfaches klicken
